apiVersion: apps/v1
kind: Deployment
metadata:
  name: matthias-topfen
  labels:
    app: matthias-topfen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matthias-topfen
  template:
    metadata:
      labels:
        app: matthias-topfen
        io.kompose.network/quarkus: "true"
    spec:
      containers:
        - name: matthias-topfen
          image: quarkus/e8v6d9d7/matthias-demo-jvm:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: quarkus-db-secret
                  key: postgres-user
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: quarkus-db-secret
                  key: postgres-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: quarkus-demo-config
                  key: quarkus-demo-url
          #- name: QUARKUS_DATASOURCE_JDBC_URL
          #   value: jdbc:postgresql://quarkus-db:5432/simplechat
---
apiVersion: v1
kind: Service
metadata:
  name: matthias-topfen
  labels:
    app: matthias-topfen
spec:
  type: LoadBalancer  # NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30111  # must be between 30000 and 32767
  selector:
    app: matthias-topfen